-- ============================================================
-- sistemaTorneo - PostgreSQL / Supabase
-- Conversión desde SQL Server
-- ============================================================

-- En Supabase NO es necesario crear la base de datos.
-- Este script crea las tablas en el esquema public.

SET search_path TO public;

-- ============================================================
-- TABLAS PRINCIPALES
-- ============================================================

CREATE TABLE torneo (
    id_torneo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(500),
    estado VARCHAR(30) NOT NULL,
    fecha_fin DATE,
    fecha_inicio DATE,
    nombre VARCHAR(150) NOT NULL
);

CREATE TABLE equipo (
    id_equipo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciudad VARCHAR(100),
    descripcion VARCHAR(500),
    escudo VARCHAR(500),
    estado VARCHAR(30) NOT NULL,
    nombre VARCHAR(150) NOT NULL
);

CREATE TABLE jugador (
    id_jugador INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apellidos VARCHAR(100) NOT NULL,
    dni VARCHAR(20),
    estado VARCHAR(30) NOT NULL,
    fecha_nacimiento DATE,
    nacionalidad VARCHAR(100),
    nombres VARCHAR(100) NOT NULL
);

-- ============================================================
-- ESTRUCTURA DEL TORNEO
-- ============================================================

CREATE TABLE fase (
    id_fase INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(500),
    nombre VARCHAR(100) NOT NULL,
    orden INTEGER NOT NULL,
    id_torneo INTEGER NOT NULL
);

CREATE TABLE serie (
    id_serie INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(500),
    nombre VARCHAR(100) NOT NULL,
    orden INTEGER NOT NULL,
    id_fase INTEGER NOT NULL
);

CREATE TABLE jornada (
    id_jornada INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100),
    numero INTEGER NOT NULL,
    id_serie INTEGER NOT NULL
);

-- ============================================================
-- PARTICIPACIONES
-- ============================================================

CREATE TABLE participacion_equipo_torneo (
    id_participacion_equipo_torneo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado VARCHAR(30) NOT NULL,
    observaciones VARCHAR(500),
    id_equipo INTEGER NOT NULL,
    id_serie INTEGER NOT NULL,
    id_torneo INTEGER NOT NULL
);

CREATE TABLE participacion_jugador_torneo (
    id_participacion_jugador_torneo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado VARCHAR(30) NOT NULL,
    fecha_registro DATE,
    numero_camiseta INTEGER,
    id_equipo INTEGER NOT NULL,
    id_jugador INTEGER NOT NULL,
    id_torneo INTEGER NOT NULL
);

-- ============================================================
-- PARTIDOS
-- ============================================================

CREATE TABLE partido (
    id_partido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado VARCHAR(30) NOT NULL,
    fecha_juego DATE,
    hora_fin TIME,
    hora_inicio TIME,
    observaciones VARCHAR(500),
    id_equipo_local INTEGER NOT NULL,
    id_equipo_visitante INTEGER NOT NULL,
    id_jornada INTEGER NOT NULL
);

CREATE TABLE participacion_jugador_partido (
    id_participacion_jugador_partido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    minutos_jugados INTEGER,
    tipo_participacion VARCHAR(20) NOT NULL,
    id_participacion_jugador_torneo INTEGER NOT NULL,
    id_partido INTEGER NOT NULL
);

CREATE TABLE gol (
    id_gol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    minuto INTEGER,
    tipo VARCHAR(30),
    id_participacion_jugador_torneo INTEGER NOT NULL,
    id_partido INTEGER NOT NULL
);

CREATE TABLE tarjeta (
    id_tarjeta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    minuto INTEGER,
    observaciones VARCHAR(500),
    tipo VARCHAR(20) NOT NULL,
    id_participacion_jugador_torneo INTEGER NOT NULL,
    id_partido INTEGER NOT NULL
);

-- ============================================================
-- SUSPENSIONES
-- ============================================================

CREATE TABLE suspension (
    id_suspension INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_jornadas INTEGER NOT NULL,
    estado VARCHAR(30) NOT NULL,
    inicio_suspension DATE,
    jornadas_cumplidas INTEGER NOT NULL,
    observaciones VARCHAR(500),
    tipo VARCHAR(30) NOT NULL,
    id_participacion_jugador_torneo INTEGER NOT NULL
);

CREATE TABLE tarjeta_de_suspension (
    id_tarjeta_de_suspension INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_suspension INTEGER NOT NULL,
    id_tarjeta INTEGER NOT NULL
);

-- ============================================================
-- RANKING
-- ============================================================

CREATE TABLE ranking_jornada (
    id_ranking_jornada INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diferencia_goles INTEGER NOT NULL,
    empatados INTEGER NOT NULL,
    ganados INTEGER NOT NULL,
    goles_contra INTEGER NOT NULL,
    goles_favor INTEGER NOT NULL,
    partidos_jugados INTEGER NOT NULL,
    perdidos INTEGER NOT NULL,
    posicion INTEGER NOT NULL,
    puntos INTEGER NOT NULL,
    id_jornada INTEGER NOT NULL,
    id_participacion_equipo_torneo INTEGER NOT NULL,
    id_serie INTEGER NOT NULL
);

-- ============================================================
-- FOREIGN KEYS
-- ============================================================

ALTER TABLE fase
    ADD CONSTRAINT fk_fase_torneo
    FOREIGN KEY (id_torneo)
    REFERENCES torneo(id_torneo);

ALTER TABLE serie
    ADD CONSTRAINT fk_serie_fase
    FOREIGN KEY (id_fase)
    REFERENCES fase(id_fase);

ALTER TABLE jornada
    ADD CONSTRAINT fk_jornada_serie
    FOREIGN KEY (id_serie)
    REFERENCES serie(id_serie);

ALTER TABLE participacion_equipo_torneo
    ADD CONSTRAINT fk_participacion_equipo_equipo
    FOREIGN KEY (id_equipo)
    REFERENCES equipo(id_equipo);

ALTER TABLE participacion_equipo_torneo
    ADD CONSTRAINT fk_participacion_equipo_serie
    FOREIGN KEY (id_serie)
    REFERENCES serie(id_serie);

ALTER TABLE participacion_equipo_torneo
    ADD CONSTRAINT fk_participacion_equipo_torneo
    FOREIGN KEY (id_torneo)
    REFERENCES torneo(id_torneo);

ALTER TABLE participacion_jugador_torneo
    ADD CONSTRAINT fk_participacion_jugador_equipo
    FOREIGN KEY (id_equipo)
    REFERENCES equipo(id_equipo);

ALTER TABLE participacion_jugador_torneo
    ADD CONSTRAINT fk_participacion_jugador_jugador
    FOREIGN KEY (id_jugador)
    REFERENCES jugador(id_jugador);

ALTER TABLE participacion_jugador_torneo
    ADD CONSTRAINT fk_participacion_jugador_torneo
    FOREIGN KEY (id_torneo)
    REFERENCES torneo(id_torneo);

ALTER TABLE partido
    ADD CONSTRAINT fk_partido_equipo_local
    FOREIGN KEY (id_equipo_local)
    REFERENCES participacion_equipo_torneo(id_participacion_equipo_torneo);

ALTER TABLE partido
    ADD CONSTRAINT fk_partido_equipo_visitante
    FOREIGN KEY (id_equipo_visitante)
    REFERENCES participacion_equipo_torneo(id_participacion_equipo_torneo);

ALTER TABLE partido
    ADD CONSTRAINT fk_partido_jornada
    FOREIGN KEY (id_jornada)
    REFERENCES jornada(id_jornada);

ALTER TABLE participacion_jugador_partido
    ADD CONSTRAINT fk_participacion_jugador_partido_jugador_torneo
    FOREIGN KEY (id_participacion_jugador_torneo)
    REFERENCES participacion_jugador_torneo(id_participacion_jugador_torneo);

ALTER TABLE participacion_jugador_partido
    ADD CONSTRAINT fk_participacion_jugador_partido_partido
    FOREIGN KEY (id_partido)
    REFERENCES partido(id_partido);

ALTER TABLE gol
    ADD CONSTRAINT fk_gol_participacion_jugador
    FOREIGN KEY (id_participacion_jugador_torneo)
    REFERENCES participacion_jugador_torneo(id_participacion_jugador_torneo);

ALTER TABLE gol
    ADD CONSTRAINT fk_gol_partido
    FOREIGN KEY (id_partido)
    REFERENCES partido(id_partido);

ALTER TABLE tarjeta
    ADD CONSTRAINT fk_tarjeta_participacion_jugador
    FOREIGN KEY (id_participacion_jugador_torneo)
    REFERENCES participacion_jugador_torneo(id_participacion_jugador_torneo);

ALTER TABLE tarjeta
    ADD CONSTRAINT fk_tarjeta_partido
    FOREIGN KEY (id_partido)
    REFERENCES partido(id_partido);

ALTER TABLE suspension
    ADD CONSTRAINT fk_suspension_participacion_jugador
    FOREIGN KEY (id_participacion_jugador_torneo)
    REFERENCES participacion_jugador_torneo(id_participacion_jugador_torneo);

ALTER TABLE tarjeta_de_suspension
    ADD CONSTRAINT fk_tarjeta_suspension_suspension
    FOREIGN KEY (id_suspension)
    REFERENCES suspension(id_suspension);

ALTER TABLE tarjeta_de_suspension
    ADD CONSTRAINT fk_tarjeta_suspension_tarjeta
    FOREIGN KEY (id_tarjeta)
    REFERENCES tarjeta(id_tarjeta);

ALTER TABLE ranking_jornada
    ADD CONSTRAINT fk_ranking_jornada
    FOREIGN KEY (id_jornada)
    REFERENCES jornada(id_jornada);

ALTER TABLE ranking_jornada
    ADD CONSTRAINT fk_ranking_participacion_equipo
    FOREIGN KEY (id_participacion_equipo_torneo)
    REFERENCES participacion_equipo_torneo(id_participacion_equipo_torneo);

ALTER TABLE ranking_jornada
    ADD CONSTRAINT fk_ranking_serie
    FOREIGN KEY (id_serie)
    REFERENCES serie(id_serie);

-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================
